<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Novolis.CodeGen.Reflection.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="TUnit" />
    <ProjectReference Include="..\..\src\Novolis.CodeGen.Reflection\Novolis.CodeGen.Reflection.csproj" />
  </ItemGroup>
</Project>
