using System.Text;

namespace Novolis.CodeGen.Bindings;

/// <summary>Provides consumer-specific documentation for generated façade types and methods.</summary>
public interface IFacadeDocumentationResolver
{
    /// <summary>Gets the type summary for a generated façade.</summary>
    /// <param name="type">The façade type being emitted.</param>
    /// <returns>A summary, or <see langword="null"/> when no documentation should be emitted.</returns>
    string? ResolveTypeSummary(FacadeTypeSpec type);

    /// <summary>Gets the method summary for a generated façade method.</summary>
    /// <param name="type">The enclosing façade type.</param>
    /// <param name="method">The façade method being emitted.</param>
    /// <returns>A summary, or <see langword="null"/> when no documentation should be emitted.</returns>
    string? ResolveMethodSummary(FacadeTypeSpec type, FacadeMethodSpec method);
}

/// <summary>Emits typed C ABI declarations as <c>LibraryImport</c> source.</summary>
public sealed class LibraryImportEmitter : IBindingEmitter
{
    /// <inheritdoc />
    public EmitStrategy Strategy => EmitStrategy.LibraryImport;

    /// <inheritdoc />
    public string Emit(EmitRequest request)
    {
        if (request.Fragment is not InteropExportsFragment fragment)
            throw new ArgumentException("LibraryImportEmitter requires an interop exports fragment.", nameof(request));

        var target = request.Target;
        if (string.IsNullOrWhiteSpace(target.ClassName) || string.IsNullOrWhiteSpace(target.Namespace))
            throw new InvalidOperationException("A library-import target requires a class name and namespace.");

        var libraryConstant = string.IsNullOrWhiteSpace(target.LibraryConstantName)
            ? "NativeLibrary"
            : target.LibraryConstantName;
        var classSummary = string.IsNullOrWhiteSpace(target.TypeSummary)
            ? $"Low-level {fragment.Id} entry points (manifest-generated <c>[LibraryImport]</c>)."
            : target.TypeSummary;
        var structSummary = string.IsNullOrWhiteSpace(target.StructSummary)
            ? "Blittable layout for a native C struct (generated from manifest)."
            : target.StructSummary;

        var sb = CreateHeader(request);
        sb.AppendLine("using System.Runtime.InteropServices;");
        if (fragment.Policy.UseDisableRuntimeMarshalling)
            sb.AppendLine("using System.Runtime.InteropServices.Marshalling;");
        foreach (var usingDirective in fragment.Usings ?? [])
            sb.AppendLine($"using {usingDirective};");
        sb.AppendLine();
        sb.AppendLine($"namespace {target.Namespace};");
        sb.AppendLine();

        foreach (var structSpec in fragment.Structs.OrderBy(s => s.Name, StringComparer.Ordinal))
        {
            sb.AppendLine($"/// <summary>{EscapeXml(structSummary)}</summary>");
            sb.AppendLine("[StructLayout(LayoutKind.Sequential)]");
            sb.AppendLine($"internal struct {structSpec.Name}");
            sb.AppendLine("{");
            foreach (var field in structSpec.Fields)
                sb.AppendLine($"    public {field.ClrType} {field.Name};");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine($"/// <summary>{classSummary}</summary>");
        sb.AppendLine($"internal static partial class {target.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine($"    private const string {libraryConstant} = \"{EscapeCSharpString(fragment.DllName)}\";");
        foreach (var import in fragment.Imports.OrderBy(i => i.Name, StringComparer.Ordinal))
        {
            EmitImport(sb, import, fragment.Policy, libraryConstant);
            sb.AppendLine();
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static StringBuilder CreateHeader(EmitRequest request)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Regenerate: {request.Context.RegenerateHint}");
        sb.AppendLine($"// ManifestSha256: {request.ManifestSha256}");
        sb.AppendLine("#nullable enable");
        return sb;
    }

    private static void EmitImport(
        StringBuilder sb,
        InteropImportSpec import,
        InteropPolicySpec policy,
        string libraryConstant)
    {
        var suppressGcTransition = ShouldSuppressGcTransition(import, policy);
        var usesUtf8 = import.Signature.Parameters.Any(p => p.Type.Kind == NativeTypeKind.Utf8String);
        EmitLibraryImportAttribute(sb, policy, libraryConstant, usesUtf8, suppressGcTransition);

        if (import.Signature.ReturnType.Kind == NativeTypeKind.Boolean)
            sb.AppendLine("    [return: MarshalAs(UnmanagedType.I1)]");

        var parameters = string.Join(", ", import.Signature.Parameters.Select(p => FormatLibraryImportParameter(p, policy)));
        sb.AppendLine(
            $"    internal static partial {import.Signature.ReturnType.CSharpTypeName} {import.Name}({parameters});");
    }

    private static bool ShouldSuppressGcTransition(InteropImportSpec import, InteropPolicySpec policy) =>
        import.SuppressGcTransition
        ?? (policy.SuppressGcTransitionByFunction.Contains(import.Name, StringComparer.Ordinal)
            && !policy.NeverSuppressGcTransition.Contains(import.Name, StringComparer.Ordinal));

    private static void EmitLibraryImportAttribute(
        StringBuilder sb,
        InteropPolicySpec policy,
        string libraryConstant,
        bool usesUtf8,
        bool suppressGcTransition)
    {
        if (policy.UseDisableRuntimeMarshalling)
        {
            if (suppressGcTransition)
                sb.AppendLine($"    [LibraryImport({libraryConstant}, SuppressGCTransition = true)]");
            else
                sb.AppendLine($"    [LibraryImport({libraryConstant})]");
            return;
        }

        if (usesUtf8 && suppressGcTransition)
            sb.AppendLine($"    [LibraryImport({libraryConstant}, StringMarshalling = StringMarshalling.Utf8, SuppressGCTransition = true)]");
        else if (usesUtf8)
            sb.AppendLine($"    [LibraryImport({libraryConstant}, StringMarshalling = StringMarshalling.Utf8)]");
        else if (suppressGcTransition)
            sb.AppendLine($"    [LibraryImport({libraryConstant}, SuppressGCTransition = true)]");
        else
            sb.AppendLine($"    [LibraryImport({libraryConstant})]");
    }

    private static string FormatLibraryImportParameter(NativeParameter parameter, InteropPolicySpec policy)
    {
        var modifier = parameter.Modifier switch
        {
            NativeParameterModifier.None => "",
            NativeParameterModifier.In => "in ",
            NativeParameterModifier.Out => "out ",
            _ => throw new ArgumentOutOfRangeException(),
        };
        var marshaller = parameter.Type.Kind == NativeTypeKind.Utf8String && policy.UseDisableRuntimeMarshalling
            ? "[MarshalUsing(typeof(Utf8StringMarshaller))] "
            : "";
        return $"{modifier}{marshaller}{parameter.Type.CSharpTypeName} {parameter.Name}";
    }

    private static string EscapeXml(string text) =>
        text.Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("<", "&lt;", StringComparison.Ordinal)
            .Replace(">", "&gt;", StringComparison.Ordinal);

    private static string EscapeCSharpString(string text) =>
        text.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);
}

/// <summary>Emits a typed C ABI dynamic-export table backed by unmanaged function pointers.</summary>
public sealed class DynamicExportsEmitter : IBindingEmitter
{
    /// <inheritdoc />
    public EmitStrategy Strategy => EmitStrategy.DynamicExports;

    /// <inheritdoc />
    public string Emit(EmitRequest request)
    {
        if (request.Fragment is not ShimExportsFragment fragment)
            throw new ArgumentException("DynamicExportsEmitter requires a shim exports fragment.", nameof(request));

        var target = request.Target;
        if (string.IsNullOrWhiteSpace(target.ClassName) || string.IsNullOrWhiteSpace(target.Namespace))
            throw new InvalidOperationException("A dynamic-export target requires a class name and namespace.");

        var sortedExports = fragment.Exports.OrderBy(e => e.Export, StringComparer.Ordinal).ToList();
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Regenerate: {request.Context.RegenerateHint}");
        sb.AppendLine($"// ManifestSha256: {request.ManifestSha256}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();
        sb.AppendLine($"namespace {target.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"internal static unsafe partial class {target.ClassName}");
        sb.AppendLine("{");

        foreach (var embeddedType in fragment.EmbeddedTypes ?? [])
        {
            sb.AppendLine("    [StructLayout(LayoutKind.Sequential)]");
            sb.AppendLine($"    internal struct {embeddedType.Name}");
            sb.AppendLine("    {");
            foreach (var field in embeddedType.Fields)
                sb.AppendLine($"        public {field.ClrType} {field.Name};");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        foreach (var export in sortedExports)
            sb.AppendLine($"    internal static {ToFunctionPointerType(export.Signature)} {export.Export}_ptr;");

        sb.AppendLine();
        sb.AppendLine("    internal static bool TryBindShim(nint module, out string? error)");
        sb.AppendLine("    {");
        sb.AppendLine("        error = null;");
        foreach (var export in sortedExports)
        {
            var functionPointerType = ToFunctionPointerType(export.Signature);
            sb.AppendLine($"        var p{export.Export} = NativeLibrary.GetExport(module, \"{export.Export}\");");
            sb.AppendLine($"        if (p{export.Export} == 0)");
            sb.AppendLine("        {");
            sb.AppendLine($"            error = \"Missing export: {export.Export}\";");
            sb.AppendLine("            return false;");
            sb.AppendLine("        }");
            sb.AppendLine($"        {export.Export}_ptr = ({functionPointerType})p{export.Export};");
        }
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string ToFunctionPointerType(NativeSignature signature)
    {
        var types = signature.Parameters.Select(ToFunctionPointerParameterType)
            .Append(ToFunctionPointerReturnType(signature.ReturnType));
        return $"delegate* unmanaged<{string.Join(", ", types)}>";
    }

    private static string ToFunctionPointerParameterType(NativeParameter parameter)
    {
        var type = parameter.Type.Kind == NativeTypeKind.Utf8String
            ? "byte*"
            : parameter.Type.CSharpTypeName;
        return parameter.Modifier switch
        {
            NativeParameterModifier.None => type,
            NativeParameterModifier.In or NativeParameterModifier.Out => $"{type}*",
            _ => throw new ArgumentOutOfRangeException(),
        };
    }

    private static string ToFunctionPointerReturnType(NativeType type) =>
        type.Kind == NativeTypeKind.Utf8String ? "byte*" : type.CSharpTypeName;
}

/// <summary>Emits thin public façade forwards from typed façade fragment data.</summary>
public sealed class FacadeForwardEmitter : IBindingEmitter
{
    private readonly IFacadeDocumentationResolver? _documentation;

    /// <summary>Creates a façade emitter with optional consumer documentation resolution.</summary>
    /// <param name="documentation">Optional resolver for generated type and method summaries.</param>
    public FacadeForwardEmitter(IFacadeDocumentationResolver? documentation = null) =>
        _documentation = documentation;

    /// <inheritdoc />
    public EmitStrategy Strategy => EmitStrategy.FacadeForward;

    /// <inheritdoc />
    public string Emit(EmitRequest request)
    {
        if (request.Fragment is not FacadeTypesFragment fragment)
            throw new ArgumentException("FacadeForwardEmitter requires a façade types fragment.", nameof(request));

        var type = fragment.Types.SingleOrDefault(t => string.Equals(t.Name, request.Target.ClassName, StringComparison.Ordinal))
            ?? throw new InvalidOperationException(
                $"Facade fragment '{fragment.Id}' does not contain type '{request.Target.ClassName}'.");
        var useInlining = string.Equals(
            request.Target.FacadeMethodImpl,
            "AggressiveInlining",
            StringComparison.Ordinal);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Regenerate: {request.Context.RegenerateHint}");
        sb.AppendLine($"// ManifestSha256: {request.ManifestSha256}");
        sb.AppendLine("#nullable enable");
        foreach (var usingDirective in type.Usings)
            sb.AppendLine($"using {usingDirective};");
        if (useInlining)
            sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine($"namespace {type.Namespace};");
        sb.AppendLine();

        var typeSummary = _documentation?.ResolveTypeSummary(type) ?? type.TypeSummary;
        if (!string.IsNullOrWhiteSpace(typeSummary))
        {
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// {EscapeXml(typeSummary.Trim())}");
            sb.AppendLine("/// </summary>");
        }
        sb.AppendLine($"public static partial class {type.Name}");
        sb.AppendLine("{");

        foreach (var method in type.Methods)
        {
            var summary = _documentation?.ResolveMethodSummary(type, method) ?? method.Summary;
            if (!string.IsNullOrWhiteSpace(summary))
            {
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {EscapeXml(summary.Trim())}");
                sb.AppendLine("    /// </summary>");
            }

            var signature = method.Signature.Trim();
            if (!signature.Contains('('))
                throw new InvalidOperationException($"Invalid façade signature for {type.Name}.{method.Name}");

            var body = method.Body.Trim().TrimEnd(';');
            if (useInlining && !body.Contains('{'))
                sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public static {signature} => {body};");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string EscapeXml(string text) =>
        text.Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("<", "&lt;", StringComparison.Ordinal)
            .Replace(">", "&gt;", StringComparison.Ordinal);
}
