using System.Text;

namespace Novolis.CodeGen.Bindings;

/// <summary>Emits a typed C ABI dynamic-export table backed by unmanaged function pointers.</summary>
public sealed class DynamicExportsEmitter : IBindingEmitter
{
    /// <inheritdoc />
    public EmitStrategy Strategy => EmitStrategy.DynamicExports;

    /// <inheritdoc />
    public string Emit(EmitRequest request)
    {
        if (request.Fragment is not ShimExportsFragment fragment)
            throw new ArgumentException("DynamicExportsEmitter requires a shim exports fragment.", nameof(request));

        var target = request.Target;
        if (string.IsNullOrWhiteSpace(target.ClassName) || string.IsNullOrWhiteSpace(target.Namespace))
            throw new InvalidOperationException("A dynamic-export target requires a class name and namespace.");

        var sortedExports = fragment.Exports.OrderBy(e => e.Export, StringComparer.Ordinal).ToList();
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Regenerate: {request.Context.RegenerateHint}");
        sb.AppendLine($"// ManifestSha256: {request.ManifestSha256}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();
        sb.AppendLine($"namespace {target.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"internal static unsafe partial class {target.ClassName}");
        sb.AppendLine("{");

        foreach (var embeddedType in fragment.EmbeddedTypes ?? [])
        {
            sb.AppendLine("    [StructLayout(LayoutKind.Sequential)]");
            sb.AppendLine($"    internal struct {embeddedType.Name}");
            sb.AppendLine("    {");
            foreach (var field in embeddedType.Fields)
                sb.AppendLine($"        public {field.ClrType} {field.Name};");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        foreach (var export in sortedExports)
            sb.AppendLine($"    internal static {ToFunctionPointerType(export.Signature)} {export.Export}_ptr;");

        sb.AppendLine();
        sb.AppendLine("    internal static bool TryBindShim(nint module, out string? error)");
        sb.AppendLine("    {");
        sb.AppendLine("        error = null;");
        foreach (var export in sortedExports)
        {
            var functionPointerType = ToFunctionPointerType(export.Signature);
            sb.AppendLine($"        var p{export.Export} = NativeLibrary.GetExport(module, \"{export.Export}\");");
            sb.AppendLine($"        if (p{export.Export} == 0)");
            sb.AppendLine("        {");
            sb.AppendLine($"            error = \"Missing export: {export.Export}\";");
            sb.AppendLine("            return false;");
            sb.AppendLine("        }");
            sb.AppendLine($"        {export.Export}_ptr = ({functionPointerType})p{export.Export};");
        }
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string ToFunctionPointerType(NativeSignature signature)
    {
        var types = signature.Parameters.Select(ToFunctionPointerParameterType)
            .Append(ToFunctionPointerReturnType(signature.ReturnType));
        return $"delegate* unmanaged<{string.Join(", ", types)}>";
    }

    private static string ToFunctionPointerParameterType(NativeParameter parameter)
    {
        var type = parameter.Type.Kind == NativeTypeKind.Utf8String
            ? "byte*"
            : parameter.Type.CSharpTypeName;
        return parameter.Modifier switch
        {
            NativeParameterModifier.None => type,
            NativeParameterModifier.In or NativeParameterModifier.Out => $"{type}*",
            _ => throw new ArgumentOutOfRangeException(),
        };
    }

    private static string ToFunctionPointerReturnType(NativeType type) =>
        type.Kind == NativeTypeKind.Utf8String ? "byte*" : type.CSharpTypeName;
}
