using System.Text;

namespace Novolis.CodeGen.Bindings;

/// <summary>Emits thin public façade forwards from typed façade fragment data.</summary>
public sealed class FacadeForwardEmitter : IBindingEmitter
{
    private readonly IFacadeDocumentationResolver? _documentation;

    /// <summary>Creates a façade emitter with optional consumer documentation resolution.</summary>
    /// <param name="documentation">Optional resolver for generated type and method summaries.</param>
    public FacadeForwardEmitter(IFacadeDocumentationResolver? documentation = null) =>
        _documentation = documentation;

    /// <inheritdoc />
    public EmitStrategy Strategy => EmitStrategy.FacadeForward;

    /// <inheritdoc />
    public string Emit(EmitRequest request)
    {
        if (request.Fragment is not FacadeTypesFragment fragment)
            throw new ArgumentException("FacadeForwardEmitter requires a façade types fragment.", nameof(request));

        var type = fragment.Types.SingleOrDefault(t => string.Equals(t.Name, request.Target.ClassName, StringComparison.Ordinal))
            ?? throw new InvalidOperationException(
                $"Facade fragment '{fragment.Id}' does not contain type '{request.Target.ClassName}'.");
        var useInlining = string.Equals(
            request.Target.FacadeMethodImpl,
            "AggressiveInlining",
            StringComparison.Ordinal);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Regenerate: {request.Context.RegenerateHint}");
        sb.AppendLine($"// ManifestSha256: {request.ManifestSha256}");
        sb.AppendLine("#nullable enable");
        foreach (var usingDirective in type.Usings)
            sb.AppendLine($"using {usingDirective};");
        if (useInlining)
            sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine($"namespace {type.Namespace};");
        sb.AppendLine();

        var typeSummary = _documentation?.ResolveTypeSummary(type) ?? type.TypeSummary;
        if (!string.IsNullOrWhiteSpace(typeSummary))
        {
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// {EscapeXml(typeSummary.Trim())}");
            sb.AppendLine("/// </summary>");
        }
        sb.AppendLine($"public static partial class {type.Name}");
        sb.AppendLine("{");

        foreach (var method in type.Methods)
        {
            var summary = _documentation?.ResolveMethodSummary(type, method) ?? method.Summary;
            if (!string.IsNullOrWhiteSpace(summary))
            {
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {EscapeXml(summary.Trim())}");
                sb.AppendLine("    /// </summary>");
            }

            var signature = method.Signature.Trim();
            if (!signature.Contains('('))
                throw new InvalidOperationException($"Invalid façade signature for {type.Name}.{method.Name}");

            var body = method.Body.Trim().TrimEnd(';');
            if (useInlining && !body.Contains('{'))
                sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public static {signature} => {body};");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string EscapeXml(string text) =>
        text.Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("<", "&lt;", StringComparison.Ordinal)
            .Replace(">", "&gt;", StringComparison.Ordinal);
}
