using System.Text;

namespace Novolis.CodeGen.Bindings;

/// <summary>Emits typed C ABI declarations as <c>LibraryImport</c> source.</summary>
public sealed class LibraryImportEmitter : IBindingEmitter
{
    /// <inheritdoc />
    public EmitStrategy Strategy => EmitStrategy.LibraryImport;

    /// <inheritdoc />
    public string Emit(EmitRequest request)
    {
        if (request.Fragment is not InteropExportsFragment fragment)
            throw new ArgumentException("LibraryImportEmitter requires an interop exports fragment.", nameof(request));

        var target = request.Target;
        if (string.IsNullOrWhiteSpace(target.ClassName) || string.IsNullOrWhiteSpace(target.Namespace))
            throw new InvalidOperationException("A library-import target requires a class name and namespace.");

        var libraryConstant = string.IsNullOrWhiteSpace(target.LibraryConstantName)
            ? "NativeLibrary"
            : target.LibraryConstantName;
        var classSummary = string.IsNullOrWhiteSpace(target.TypeSummary)
            ? $"Low-level {fragment.Id} entry points (manifest-generated <c>[LibraryImport]</c>)."
            : target.TypeSummary;
        var structSummary = string.IsNullOrWhiteSpace(target.StructSummary)
            ? "Blittable layout for a native C struct (generated from manifest)."
            : target.StructSummary;

        var sb = CreateHeader(request);
        sb.AppendLine("using System.Runtime.InteropServices;");
        if (fragment.Policy.UseDisableRuntimeMarshalling)
            sb.AppendLine("using System.Runtime.InteropServices.Marshalling;");
        foreach (var usingDirective in fragment.Usings ?? [])
            sb.AppendLine($"using {usingDirective};");
        sb.AppendLine();
        sb.AppendLine($"namespace {target.Namespace};");
        sb.AppendLine();

        foreach (var structSpec in fragment.Structs.OrderBy(s => s.Name, StringComparer.Ordinal))
        {
            sb.AppendLine($"/// <summary>{EscapeXml(structSummary)}</summary>");
            sb.AppendLine("[StructLayout(LayoutKind.Sequential)]");
            sb.AppendLine($"internal struct {structSpec.Name}");
            sb.AppendLine("{");
            foreach (var field in structSpec.Fields)
                sb.AppendLine($"    public {field.ClrType} {field.Name};");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine($"/// <summary>{classSummary}</summary>");
        sb.AppendLine($"internal static partial class {target.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine($"    private const string {libraryConstant} = \"{EscapeCSharpString(fragment.DllName)}\";");
        foreach (var import in fragment.Imports.OrderBy(i => i.Name, StringComparer.Ordinal))
        {
            EmitImport(sb, import, fragment.Policy, libraryConstant);
            sb.AppendLine();
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static StringBuilder CreateHeader(EmitRequest request)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Regenerate: {request.Context.RegenerateHint}");
        sb.AppendLine($"// ManifestSha256: {request.ManifestSha256}");
        sb.AppendLine("#nullable enable");
        return sb;
    }

    private static void EmitImport(
        StringBuilder sb,
        InteropImportSpec import,
        InteropPolicySpec policy,
        string libraryConstant)
    {
        var suppressGcTransition = ShouldSuppressGcTransition(import, policy);
        var usesUtf8 = import.Signature.Parameters.Any(p => p.Type.Kind == NativeTypeKind.Utf8String);
        EmitLibraryImportAttribute(sb, policy, libraryConstant, usesUtf8, suppressGcTransition);

        if (import.Signature.ReturnType.Kind == NativeTypeKind.Boolean)
            sb.AppendLine("    [return: MarshalAs(UnmanagedType.I1)]");

        var parameters = string.Join(", ", import.Signature.Parameters.Select(p => FormatLibraryImportParameter(p, policy)));
        sb.AppendLine(
            $"    internal static partial {import.Signature.ReturnType.CSharpTypeName} {import.Name}({parameters});");
    }

    private static bool ShouldSuppressGcTransition(InteropImportSpec import, InteropPolicySpec policy) =>
        import.SuppressGcTransition
        ?? (policy.SuppressGcTransitionByFunction.Contains(import.Name, StringComparer.Ordinal)
            && !policy.NeverSuppressGcTransition.Contains(import.Name, StringComparer.Ordinal));

    private static void EmitLibraryImportAttribute(
        StringBuilder sb,
        InteropPolicySpec policy,
        string libraryConstant,
        bool usesUtf8,
        bool suppressGcTransition)
    {
        if (policy.UseDisableRuntimeMarshalling)
        {
            if (suppressGcTransition)
                sb.AppendLine($"    [LibraryImport({libraryConstant}, SuppressGCTransition = true)]");
            else
                sb.AppendLine($"    [LibraryImport({libraryConstant})]");
            return;
        }

        if (usesUtf8 && suppressGcTransition)
            sb.AppendLine($"    [LibraryImport({libraryConstant}, StringMarshalling = StringMarshalling.Utf8, SuppressGCTransition = true)]");
        else if (usesUtf8)
            sb.AppendLine($"    [LibraryImport({libraryConstant}, StringMarshalling = StringMarshalling.Utf8)]");
        else if (suppressGcTransition)
            sb.AppendLine($"    [LibraryImport({libraryConstant}, SuppressGCTransition = true)]");
        else
            sb.AppendLine($"    [LibraryImport({libraryConstant})]");
    }

    private static string FormatLibraryImportParameter(NativeParameter parameter, InteropPolicySpec policy)
    {
        var modifier = parameter.Modifier switch
        {
            NativeParameterModifier.None => "",
            NativeParameterModifier.In => "in ",
            NativeParameterModifier.Out => "out ",
            _ => throw new ArgumentOutOfRangeException(),
        };
        var marshaller = parameter.Type.Kind == NativeTypeKind.Utf8String && policy.UseDisableRuntimeMarshalling
            ? "[MarshalUsing(typeof(Utf8StringMarshaller))] "
            : "";
        return $"{modifier}{marshaller}{parameter.Type.CSharpTypeName} {parameter.Name}";
    }

    private static string EscapeXml(string text) =>
        text.Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("<", "&lt;", StringComparison.Ordinal)
            .Replace(">", "&gt;", StringComparison.Ordinal);

    private static string EscapeCSharpString(string text) =>
        text.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);
}
